apiVersion: skaffold/v4beta14
kind: Config
build:
  artifacts:
    - image: bigdahn/blog-auth
      context: auth
      sync:
        infer:
          - "src/**/*.ts"
      docker:
        dockerfile: Dockerfile
    - image: bigdahn/blog-post
      context: posts
      sync:
        infer:
          - "src/**/*.ts"
      docker:
        dockerfile: Dockerfile
    - image: bigdahn/blog-comment
      context: comments
      sync:
        infer:
          - "src/**/*.ts"
      docker:
        dockerfile: Dockerfile
  local:
    push: false
manifests:
  rawYaml:
    - ./infra/k8s/*
deploy:
  kubectl: {}
