apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-delivery-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog-delivery
  template:
    metadata:
      labels:
        app: blog-delivery
    spec:
      containers:
        - name: blog-delivery
          image: bigdahn/blog-delivery
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: bloggie
            - name: REDIS_HOST
              value: redis-srv
            - name: REDIS_PORT
              value: '6379'
            - name: EMAIL_HOST
              valuefrom:
                secretKeyRef:
                  name: email-host
                  key: EMAIL_HOST
            - name: EMAIL_PORT
              valuefrom:
                secretKeyRef:
                  name: email-port
                  key: EMAIL_PORT
            - name: EMAIL_USER
              valuefrom:
                secretKeyRef:
                  name: email-user
                  key: EMAIL_USER
            - name: EMAIL_PASSWORD
              valuefrom:
                secretKeyRef:
                  name: email-password
                  key: EMAIL_PASSWORD
